import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NextJs ToDo List',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en"> 
      <body className={inter.className}>
        <div className=' p-6 bg-background-image h-screen bg-no-repeat bg-cover'>
          <Navbar  /> 
          {children}
        </div>
      </body>
    </html>
  )
}
